name: todo
description: A simple todo list app using https://jsonplaceholder.typicode.com

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  hive_flutter: ^1.1.0
  http: ^0.13.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
